export const categories = ['All', 'Business', 'Art', 'Construction', 'Tech', 'Home', 'Lifestyle']

export const services = [
  {
    id: 1,
    title: 'Kivuli Carpentry',
    category: 'Custom Furniture',
    providerName: 'David O.',
    providerAvatar: 'https://i.pravatar.cc/150?u=david',
    rating: 4.9,
    verified: true,
    image: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&q=80',
    review: '"Excellent dining table!"',
  },
  {
    id: 2,
    title: "Amina's Threads",
    category: 'Handwoven Textiles',
    providerName: 'Amina K.',
    providerAvatar: 'https://i.pravatar.cc/150?u=amina',
    rating: 4.8,
    verified: true,
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&q=80',
    review: '"Beautiful vibrant colors"',
  },
  {
    id: 3,
    title: 'Tech Fixers',
    category: 'Device Repair',
    providerName: 'Sam T.',
    providerAvatar: 'https://i.pravatar.cc/150?u=sam',
    rating: 4.7,
    verified: false,
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&q=80',
    review: '"Fixed my phone screen fast"',
  },
  {
    id: 4,
    title: 'Fresh Bakes',
    category: 'Custom Cakes',
    providerName: 'Sarah M.',
    providerAvatar: 'https://i.pravatar.cc/150?u=sarah',
    rating: 5.0,
    verified: true,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80',
    review: '"Best cake in town!"',
  },
]

export const posts = [
  {
    id: 1,
    userName: 'David O.',
    userAvatar: 'https://i.pravatar.cc/150?u=david',
    verified: true,
    time: '2h ago',
    caption:
      'Just finished this custom pipe fitting project for a client in Nairobi. Always great to see raw materials turn into functional art. #plumbing #craftsmanship #nairobi',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80',
    likes: 24,
    comments: 5,
    shares: 5,
  },
  {
    id: 2,
    userName: 'Sarah M.',
    userAvatar: 'https://i.pravatar.cc/150?u=sarah',
    verified: true,
    time: '4h ago',
    caption:
      'Fresh batch of organic honey and preserves ready for the weekend market! Come find us at our usual spot. Special discount for returning customers! 🍯🥬',
    image: 'https://images.unsplash.com/photo-1587049352847-4d4b126a71ea?w=800&q=80',
    likes: 56,
    comments: 12,
    shares: 8,
  },
  {
    id: 3,
    userName: 'John K.',
    userAvatar: 'https://i.pravatar.cc/150?u=john',
    verified: false,
    time: '5h ago',
    caption:
      'Finally upgraded the workshop tools. Ready to take on more complex wood carving commissions. Send me a DM if you need custom pieces!',
    image: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800&q=80',
    likes: 18,
    comments: 2,
    shares: 1,
  },
  {
    id: 4,
    userName: 'Amina K.',
    userAvatar: 'https://i.pravatar.cc/150?u=amina',
    verified: true,
    time: '1d ago',
    caption:
      "Working on a new collection of handwoven fabrics. The colors are inspired by the sunset over the Mara. Can't wait to share the final pieces!",
    image: 'https://images.unsplash.com/photo-1605371924599-2d0365da1ae0?w=800&q=80',
    likes: 89,
    comments: 22,
    shares: 15,
  },
  {
    id: 5,
    userName: 'Peter N.',
    userAvatar: 'https://i.pravatar.cc/150?u=peter',
    verified: true,
    time: '1d ago',
    caption:
      "Quick tip: Always check your car's tire pressure before a long trip. Had 3 customers today who could have avoided a blowout! Drive safe everyone. 🚗🔧",
    image: 'https://images.unsplash.com/photo-1486262715619-673322509c1b?w=800&q=80',
    likes: 112,
    comments: 14,
    shares: 30,
  },
  {
    id: 6,
    userName: 'Grace W.',
    userAvatar: 'https://i.pravatar.cc/150?u=grace',
    verified: false,
    time: '2d ago',
    caption:
      'Just restocked our popular Shea Butter lotions! Get yours before they run out again. Perfect for this dry weather.',
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80',
    likes: 45,
    comments: 8,
    shares: 3,
  },
  {
    id: 7,
    userName: 'Kevin O.',
    userAvatar: 'https://i.pravatar.cc/150?u=kevin',
    verified: true,
    time: '2d ago',
    caption:
      'Another successful home installation. Solar panels are the way to go for reliable energy. Message me for a free quote on your home.',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80',
    likes: 67,
    comments: 11,
    shares: 12,
  },
  {
    id: 8,
    userName: 'Mary J.',
    userAvatar: 'https://i.pravatar.cc/150?u=mary',
    verified: true,
    time: '3d ago',
    caption:
      'Baking all morning! Wedding season is here and we are fully booked for the next two weeks. Thank you for your continued support Jamii!',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80',
    likes: 150,
    comments: 34,
    shares: 5,
  },
  {
    id: 9,
    userName: 'Brian T.',
    userAvatar: 'https://i.pravatar.cc/150?u=brian',
    verified: false,
    time: '4d ago',
    caption:
      'Does anyone know a good reliable supplier for raw leather in the CBD area? Asking for a new bag project I am working on.',
    image: null,
    likes: 12,
    comments: 18,
    shares: 0,
  },
  {
    id: 10,
    userName: 'Lilian M.',
    userAvatar: 'https://i.pravatar.cc/150?u=lilian',
    verified: true,
    time: '5d ago',
    caption:
      "Event decor from this weekend's graduation party. We went with a gold and green theme. So happy with how it turned out!",
    image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=80',
    likes: 210,
    comments: 45,
    shares: 20,
  },
]
